/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.Account = factory(root.S4sFull.ApiClient, root.S4sFull.User);
  }
}(this, function(ApiClient, User) {
  'use strict';




  /**
   * The Account model module.
   * @module model/Account
   * @version stable
   */

  /**
   * Constructs a new <code>Account</code>.
   * Model description
   * @alias module:model/Account
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>Account</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Account} obj Optional instance to populate.
   * @return {module:model/Account} The populated <code>Account</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('privateData')) {
        obj['privateData'] = ApiClient.convertToType(data['privateData'], {'String': 'String'});
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], {'String': 'String'});
      }
      if (data.hasOwnProperty('defaultUserId')) {
        obj['defaultUserId'] = ApiClient.convertToType(data['defaultUserId'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('defaultUser')) {
        obj['defaultUser'] = User.constructFromObject(data['defaultUser']);
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('typ')) {
        obj['typ'] = ApiClient.convertToType(data['typ'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Object.<String, String>} privateData
   */
  exports.prototype['privateData'] = undefined;
  /**
   * @member {Object.<String, String>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {String} defaultUserId
   */
  exports.prototype['defaultUserId'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/User} defaultUser
   */
  exports.prototype['defaultUser'] = undefined;
  /**
   * @member {module:model/Account.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} typ
   */
  exports.prototype['typ'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "WaitingAprove"
     * @const
     */
    "WaitingAprove": "WaitingAprove",
    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved"  };


  return exports;
}));


