/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.CustomerPlan = factory(root.S4sFull.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CustomerPlan model module.
   * @module model/CustomerPlan
   * @version stable
   */

  /**
   * Constructs a new <code>CustomerPlan</code>.
   * Model description
   * @alias module:model/CustomerPlan
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>CustomerPlan</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerPlan} obj Optional instance to populate.
   * @return {module:model/CustomerPlan} The populated <code>CustomerPlan</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('currentBillId')) {
        obj['currentBillId'] = ApiClient.convertToType(data['currentBillId'], 'String');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Integer');
      }
      if (data.hasOwnProperty('endPeriodToPlanId')) {
        obj['endPeriodToPlanId'] = ApiClient.convertToType(data['endPeriodToPlanId'], 'String');
      }
      if (data.hasOwnProperty('swapPlanId')) {
        obj['swapPlanId'] = ApiClient.convertToType(data['swapPlanId'], 'String');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('packId')) {
        obj['packId'] = ApiClient.convertToType(data['packId'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('totalInPayment')) {
        obj['totalInPayment'] = ApiClient.convertToType(data['totalInPayment'], {'String': 'Integer'});
      }
      if (data.hasOwnProperty('planId')) {
        obj['planId'] = ApiClient.convertToType(data['planId'], 'String');
      }
      if (data.hasOwnProperty('family')) {
        obj['family'] = ApiClient.convertToType(data['family'], 'String');
      }
      if (data.hasOwnProperty('onExpirePlanId')) {
        obj['onExpirePlanId'] = ApiClient.convertToType(data['onExpirePlanId'], 'String');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {String} currentBillId
   */
  exports.prototype['currentBillId'] = undefined;
  /**
   * @member {Integer} endDate
   */
  exports.prototype['endDate'] = undefined;
  /**
   * @member {String} endPeriodToPlanId
   */
  exports.prototype['endPeriodToPlanId'] = undefined;
  /**
   * @member {String} swapPlanId
   */
  exports.prototype['swapPlanId'] = undefined;
  /**
   * @member {String} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} packId
   */
  exports.prototype['packId'] = undefined;
  /**
   * @member {module:model/CustomerPlan.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Object.<String, Integer>} totalInPayment
   */
  exports.prototype['totalInPayment'] = undefined;
  /**
   * @member {String} planId
   */
  exports.prototype['planId'] = undefined;
  /**
   * @member {String} family
   */
  exports.prototype['family'] = undefined;
  /**
   * @member {String} onExpirePlanId
   */
  exports.prototype['onExpirePlanId'] = undefined;
  /**
   * @member {Integer} startDate
   */
  exports.prototype['startDate'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "History"
     * @const
     */
    "History": "History",
    /**
     * value: "Enjoy"
     * @const
     */
    "Enjoy": "Enjoy"  };


  return exports;
}));


