/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResourceStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResourceStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.CustomerPack = factory(root.S4sFull.ApiClient, root.S4sFull.ResourceStatus);
  }
}(this, function(ApiClient, ResourceStatus) {
  'use strict';




  /**
   * The CustomerPack model module.
   * @module model/CustomerPack
   * @version stable
   */

  /**
   * Constructs a new <code>CustomerPack</code>.
   * Model description
   * @alias module:model/CustomerPack
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>CustomerPack</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerPack} obj Optional instance to populate.
   * @return {module:model/CustomerPack} The populated <code>CustomerPack</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('closedTime')) {
        obj['closedTime'] = ApiClient.convertToType(data['closedTime'], 'Integer');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('resourceStatuList')) {
        obj['resourceStatuList'] = ApiClient.convertToType(data['resourceStatuList'], [ResourceStatus]);
      }
      if (data.hasOwnProperty('subscriptionId')) {
        obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'String');
      }
      if (data.hasOwnProperty('expirationTimeSpan')) {
        obj['expirationTimeSpan'] = ApiClient.convertToType(data['expirationTimeSpan'], 'Integer');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('exactConfId')) {
        obj['exactConfId'] = ApiClient.convertToType(data['exactConfId'], 'String');
      }
      if (data.hasOwnProperty('packId')) {
        obj['packId'] = ApiClient.convertToType(data['packId'], 'String');
      }
      if (data.hasOwnProperty('spent')) {
        obj['spent'] = ApiClient.convertToType(data['spent'], {'String': 'Integer'});
      }
      if (data.hasOwnProperty('creationTime')) {
        obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} closedTime
   */
  exports.prototype['closedTime'] = undefined;
  /**
   * @member {module:model/CustomerPack.StateEnum} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {Array.<module:model/ResourceStatus>} resourceStatuList
   */
  exports.prototype['resourceStatuList'] = undefined;
  /**
   * @member {String} subscriptionId
   */
  exports.prototype['subscriptionId'] = undefined;
  /**
   * @member {Integer} expirationTimeSpan
   */
  exports.prototype['expirationTimeSpan'] = undefined;
  /**
   * @member {String} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} exactConfId
   */
  exports.prototype['exactConfId'] = undefined;
  /**
   * @member {String} packId
   */
  exports.prototype['packId'] = undefined;
  /**
   * @member {Object.<String, Integer>} spent
   */
  exports.prototype['spent'] = undefined;
  /**
   * @member {Integer} creationTime
   */
  exports.prototype['creationTime'] = undefined;


  /**
   * Allowed values for the <code>state</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StateEnum = {
    /**
     * value: "History"
     * @const
     */
    "History": "History",
    /**
     * value: "Closing"
     * @const
     */
    "Closing": "Closing",
    /**
     * value: "Enjoy"
     * @const
     */
    "Enjoy": "Enjoy",
    /**
     * value: "Creating"
     * @const
     */
    "Creating": "Creating"  };


  return exports;
}));


