/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.CustomerPackSubscription = factory(root.S4sFull.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CustomerPackSubscription model module.
   * @module model/CustomerPackSubscription
   * @version stable
   */

  /**
   * Constructs a new <code>CustomerPackSubscription</code>.
   * Model description
   * @alias module:model/CustomerPackSubscription
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>CustomerPackSubscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerPackSubscription} obj Optional instance to populate.
   * @return {module:model/CustomerPackSubscription} The populated <code>CustomerPackSubscription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('closedTime')) {
        obj['closedTime'] = ApiClient.convertToType(data['closedTime'], 'Integer');
      }
      if (data.hasOwnProperty('currentEnjoyId')) {
        obj['currentEnjoyId'] = ApiClient.convertToType(data['currentEnjoyId'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('packId')) {
        obj['packId'] = ApiClient.convertToType(data['packId'], 'String');
      }
      if (data.hasOwnProperty('creationTime')) {
        obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} closedTime
   */
  exports.prototype['closedTime'] = undefined;
  /**
   * @member {String} currentEnjoyId
   */
  exports.prototype['currentEnjoyId'] = undefined;
  /**
   * @member {module:model/CustomerPackSubscription.StateEnum} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} packId
   */
  exports.prototype['packId'] = undefined;
  /**
   * @member {Integer} creationTime
   */
  exports.prototype['creationTime'] = undefined;


  /**
   * Allowed values for the <code>state</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StateEnum = {
    /**
     * value: "History"
     * @const
     */
    "History": "History",
    /**
     * value: "Enjoy"
     * @const
     */
    "Enjoy": "Enjoy"  };


  return exports;
}));


