/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.GoogleTokenId = factory(root.S4sFull.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GoogleTokenId model module.
   * @module model/GoogleTokenId
   * @version stable
   */

  /**
   * Constructs a new <code>GoogleTokenId</code>.
   * Model description
   * @alias module:model/GoogleTokenId
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>GoogleTokenId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GoogleTokenId} obj Optional instance to populate.
   * @return {module:model/GoogleTokenId} The populated <code>GoogleTokenId</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('email_verified')) {
        obj['email_verified'] = ApiClient.convertToType(data['email_verified'], 'Boolean');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('exp')) {
        obj['exp'] = ApiClient.convertToType(data['exp'], 'Integer');
      }
      if (data.hasOwnProperty('profile')) {
        obj['profile'] = ApiClient.convertToType(data['profile'], 'String');
      }
      if (data.hasOwnProperty('picture')) {
        obj['picture'] = ApiClient.convertToType(data['picture'], 'String');
      }
      if (data.hasOwnProperty('iat')) {
        obj['iat'] = ApiClient.convertToType(data['iat'], 'Integer');
      }
      if (data.hasOwnProperty('sub')) {
        obj['sub'] = ApiClient.convertToType(data['sub'], 'String');
      }
      if (data.hasOwnProperty('at_hash')) {
        obj['at_hash'] = ApiClient.convertToType(data['at_hash'], 'String');
      }
      if (data.hasOwnProperty('azp')) {
        obj['azp'] = ApiClient.convertToType(data['azp'], 'String');
      }
      if (data.hasOwnProperty('aud')) {
        obj['aud'] = ApiClient.convertToType(data['aud'], 'String');
      }
      if (data.hasOwnProperty('hd')) {
        obj['hd'] = ApiClient.convertToType(data['hd'], 'String');
      }
      if (data.hasOwnProperty('iss')) {
        obj['iss'] = ApiClient.convertToType(data['iss'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Boolean} email_verified
   */
  exports.prototype['email_verified'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {Integer} exp
   */
  exports.prototype['exp'] = undefined;
  /**
   * @member {String} profile
   */
  exports.prototype['profile'] = undefined;
  /**
   * @member {String} picture
   */
  exports.prototype['picture'] = undefined;
  /**
   * @member {Integer} iat
   */
  exports.prototype['iat'] = undefined;
  /**
   * @member {String} sub
   */
  exports.prototype['sub'] = undefined;
  /**
   * @member {String} at_hash
   */
  exports.prototype['at_hash'] = undefined;
  /**
   * @member {String} azp
   */
  exports.prototype['azp'] = undefined;
  /**
   * @member {String} aud
   */
  exports.prototype['aud'] = undefined;
  /**
   * @member {String} hd
   */
  exports.prototype['hd'] = undefined;
  /**
   * @member {String} iss
   */
  exports.prototype['iss'] = undefined;



  return exports;
}));


