/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Price'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Price'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.PaymentRequest = factory(root.S4sFull.ApiClient, root.S4sFull.Price);
  }
}(this, function(ApiClient, Price) {
  'use strict';




  /**
   * The PaymentRequest model module.
   * @module model/PaymentRequest
   * @version stable
   */

  /**
   * Constructs a new <code>PaymentRequest</code>.
   * Model description
   * @alias module:model/PaymentRequest
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>PaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentRequest} obj Optional instance to populate.
   * @return {module:model/PaymentRequest} The populated <code>PaymentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('creationTimespan')) {
        obj['creationTimespan'] = ApiClient.convertToType(data['creationTimespan'], 'Integer');
      }
      if (data.hasOwnProperty('paidTimespan')) {
        obj['paidTimespan'] = ApiClient.convertToType(data['paidTimespan'], 'Integer');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('whatPays')) {
        obj['whatPays'] = ApiClient.convertToType(data['whatPays'], {'String': 'Integer'});
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = Price.constructFromObject(data['price']);
      }
      if (data.hasOwnProperty('billId')) {
        obj['billId'] = ApiClient.convertToType(data['billId'], 'String');
      }
      if (data.hasOwnProperty('customerId')) {
        obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('stripeChargeId')) {
        obj['stripeChargeId'] = ApiClient.convertToType(data['stripeChargeId'], 'String');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} creationTimespan
   */
  exports.prototype['creationTimespan'] = undefined;
  /**
   * @member {Integer} paidTimespan
   */
  exports.prototype['paidTimespan'] = undefined;
  /**
   * @member {module:model/PaymentRequest.StateEnum} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {Object.<String, Integer>} whatPays
   */
  exports.prototype['whatPays'] = undefined;
  /**
   * @member {module:model/Price} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {String} billId
   */
  exports.prototype['billId'] = undefined;
  /**
   * @member {String} customerId
   */
  exports.prototype['customerId'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} stripeChargeId
   */
  exports.prototype['stripeChargeId'] = undefined;
  /**
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * @member {Integer} value
   */
  exports.prototype['value'] = undefined;


  /**
   * Allowed values for the <code>state</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StateEnum = {
    /**
     * value: "status2WaitPayment"
     * @const
     */
    "status2WaitPayment": "status2WaitPayment",
    /**
     * value: "status3Canceled"
     * @const
     */
    "status3Canceled": "status3Canceled",
    /**
     * value: "status4Paid"
     * @const
     */
    "status4Paid": "status4Paid",
    /**
     * value: "status1Failed"
     * @const
     */
    "status1Failed": "status1Failed",
    /**
     * value: "status3Paid"
     * @const
     */
    "status3Paid": "status3Paid"  };


  return exports;
}));


