/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaymentPaypal', 'model/StripeConf'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PaymentPaypal'), require('./StripeConf'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.PaymentConf = factory(root.S4sFull.ApiClient, root.S4sFull.PaymentPaypal, root.S4sFull.StripeConf);
  }
}(this, function(ApiClient, PaymentPaypal, StripeConf) {
  'use strict';




  /**
   * The PaymentConf model module.
   * @module model/PaymentConf
   * @version stable
   */

  /**
   * Constructs a new <code>PaymentConf</code>.
   * Model description
   * @alias module:model/PaymentConf
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PaymentConf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentConf} obj Optional instance to populate.
   * @return {module:model/PaymentConf} The populated <code>PaymentConf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('paypal')) {
        obj['paypal'] = PaymentPaypal.constructFromObject(data['paypal']);
      }
      if (data.hasOwnProperty('stripe')) {
        obj['stripe'] = StripeConf.constructFromObject(data['stripe']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PaymentPaypal} paypal
   */
  exports.prototype['paypal'] = undefined;
  /**
   * @member {module:model/StripeConf} stripe
   */
  exports.prototype['stripe'] = undefined;



  return exports;
}));


