/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PricingUiConfPlan', 'model/PricingUiConfResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PricingUiConfPlan'), require('./PricingUiConfResource'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.PricingUiConfPack = factory(root.S4sFull.ApiClient, root.S4sFull.PricingUiConfPlan, root.S4sFull.PricingUiConfResource);
  }
}(this, function(ApiClient, PricingUiConfPlan, PricingUiConfResource) {
  'use strict';




  /**
   * The PricingUiConfPack model module.
   * @module model/PricingUiConfPack
   * @version stable
   */

  /**
   * Constructs a new <code>PricingUiConfPack</code>.
   * Model description
   * @alias module:model/PricingUiConfPack
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>PricingUiConfPack</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PricingUiConfPack} obj Optional instance to populate.
   * @return {module:model/PricingUiConfPack} The populated <code>PricingUiConfPack</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('order')) {
        obj['order'] = ApiClient.convertToType(data['order'], 'Integer');
      }
      if (data.hasOwnProperty('isVisible')) {
        obj['isVisible'] = ApiClient.convertToType(data['isVisible'], 'Boolean');
      }
      if (data.hasOwnProperty('resources')) {
        obj['resources'] = ApiClient.convertToType(data['resources'], [PricingUiConfResource]);
      }
      if (data.hasOwnProperty('plans')) {
        obj['plans'] = ApiClient.convertToType(data['plans'], {'String': PricingUiConfPlan});
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Integer} order
   */
  exports.prototype['order'] = undefined;
  /**
   * @member {Boolean} isVisible
   */
  exports.prototype['isVisible'] = undefined;
  /**
   * @member {Array.<module:model/PricingUiConfResource>} resources
   */
  exports.prototype['resources'] = undefined;
  /**
   * @member {Object.<String, module:model/PricingUiConfPlan>} plans
   */
  exports.prototype['plans'] = undefined;



  return exports;
}));


