/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.PricingUiConfPlan = factory(root.S4sFull.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PricingUiConfPlan model module.
   * @module model/PricingUiConfPlan
   * @version stable
   */

  /**
   * Constructs a new <code>PricingUiConfPlan</code>.
   * Model description
   * @alias module:model/PricingUiConfPlan
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>PricingUiConfPlan</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PricingUiConfPlan} obj Optional instance to populate.
   * @return {module:model/PricingUiConfPlan} The populated <code>PricingUiConfPlan</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mainPrice')) {
        obj['mainPrice'] = ApiClient.convertToType(data['mainPrice'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('order')) {
        obj['order'] = ApiClient.convertToType(data['order'], 'Integer');
      }
      if (data.hasOwnProperty('isVisible')) {
        obj['isVisible'] = ApiClient.convertToType(data['isVisible'], 'Boolean');
      }
      if (data.hasOwnProperty('mainVariableCost')) {
        obj['mainVariableCost'] = ApiClient.convertToType(data['mainVariableCost'], 'String');
      }
      if (data.hasOwnProperty('period')) {
        obj['period'] = ApiClient.convertToType(data['period'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PricingUiConfPlan.MainPriceEnum} mainPrice
   */
  exports.prototype['mainPrice'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Integer} order
   */
  exports.prototype['order'] = undefined;
  /**
   * @member {Boolean} isVisible
   */
  exports.prototype['isVisible'] = undefined;
  /**
   * @member {String} mainVariableCost
   */
  exports.prototype['mainVariableCost'] = undefined;
  /**
   * @member {module:model/PricingUiConfPlan.PeriodEnum} period
   */
  exports.prototype['period'] = undefined;


  /**
   * Allowed values for the <code>mainPrice</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MainPriceEnum = {
    /**
     * value: "VariableCost"
     * @const
     */
    "VariableCost": "VariableCost",
    /**
     * value: "PeriodicCost"
     * @const
     */
    "PeriodicCost": "PeriodicCost",
    /**
     * value: "Setup"
     * @const
     */
    "Setup": "Setup",
    /**
     * value: "Cost"
     * @const
     */
    "Cost": "Cost"  };

  /**
   * Allowed values for the <code>period</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PeriodEnum = {
    /**
     * value: "Year"
     * @const
     */
    "Year": "Year",
    /**
     * value: "Month"
     * @const
     */
    "Month": "Month",
    /**
     * value: "Week"
     * @const
     */
    "Week": "Week",
    /**
     * value: "Day"
     * @const
     */
    "Day": "Day"  };


  return exports;
}));


