/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PricingTablePlanCost', 'model/PricingTableResource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PricingTablePlanCost'), require('./PricingTableResource'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.PricingTable2Plan = factory(root.S4sFull.ApiClient, root.S4sFull.PricingTablePlanCost, root.S4sFull.PricingTableResource);
  }
}(this, function(ApiClient, PricingTablePlanCost, PricingTableResource) {
  'use strict';




  /**
   * The PricingTable2Plan model module.
   * @module model/PricingTable2Plan
   * @version stable
   */

  /**
   * Constructs a new <code>PricingTable2Plan</code>.
   * Model description
   * @alias module:model/PricingTable2Plan
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>PricingTable2Plan</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PricingTable2Plan} obj Optional instance to populate.
   * @return {module:model/PricingTable2Plan} The populated <code>PricingTable2Plan</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('costMain')) {
        obj['costMain'] = PricingTablePlanCost.constructFromObject(data['costMain']);
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('requirePaymentMethod')) {
        obj['requirePaymentMethod'] = ApiClient.convertToType(data['requirePaymentMethod'], 'Boolean');
      }
      if (data.hasOwnProperty('packId')) {
        obj['packId'] = ApiClient.convertToType(data['packId'], 'String');
      }
      if (data.hasOwnProperty('typ')) {
        obj['typ'] = ApiClient.convertToType(data['typ'], 'String');
      }
      if (data.hasOwnProperty('resources')) {
        obj['resources'] = ApiClient.convertToType(data['resources'], [PricingTableResource]);
      }
      if (data.hasOwnProperty('costList')) {
        obj['costList'] = ApiClient.convertToType(data['costList'], [PricingTablePlanCost]);
      }
      if (data.hasOwnProperty('planId')) {
        obj['planId'] = ApiClient.convertToType(data['planId'], 'String');
      }
      if (data.hasOwnProperty('subscribeUrl')) {
        obj['subscribeUrl'] = ApiClient.convertToType(data['subscribeUrl'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/PricingTablePlanCost} costMain
   */
  exports.prototype['costMain'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Boolean} requirePaymentMethod
   */
  exports.prototype['requirePaymentMethod'] = undefined;
  /**
   * @member {String} packId
   */
  exports.prototype['packId'] = undefined;
  /**
   * @member {module:model/PricingTable2Plan.TypEnum} typ
   */
  exports.prototype['typ'] = undefined;
  /**
   * @member {Array.<module:model/PricingTableResource>} resources
   */
  exports.prototype['resources'] = undefined;
  /**
   * @member {Array.<module:model/PricingTablePlanCost>} costList
   */
  exports.prototype['costList'] = undefined;
  /**
   * @member {String} planId
   */
  exports.prototype['planId'] = undefined;
  /**
   * @member {String} subscribeUrl
   */
  exports.prototype['subscribeUrl'] = undefined;


  /**
   * Allowed values for the <code>typ</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypEnum = {
    /**
     * value: "OneTimePay"
     * @const
     */
    "OneTimePay": "OneTimePay",
    /**
     * value: "Subscription"
     * @const
     */
    "Subscription": "Subscription"  };


  return exports;
}));


