/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.PricingPolicy = factory(root.S4sFull.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PricingPolicy model module.
   * @module model/PricingPolicy
   * @version stable
   */

  /**
   * Constructs a new <code>PricingPolicy</code>.
   * Model description
   * @alias module:model/PricingPolicy
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PricingPolicy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PricingPolicy} obj Optional instance to populate.
   * @return {module:model/PricingPolicy} The populated <code>PricingPolicy</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('upgrade')) {
        obj['upgrade'] = ApiClient.convertToType(data['upgrade'], 'String');
      }
      if (data.hasOwnProperty('downgrade')) {
        obj['downgrade'] = ApiClient.convertToType(data['downgrade'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PricingPolicy.UpgradeEnum} upgrade
   */
  exports.prototype['upgrade'] = undefined;
  /**
   * @member {module:model/PricingPolicy.DowngradeEnum} downgrade
   */
  exports.prototype['downgrade'] = undefined;


  /**
   * Allowed values for the <code>upgrade</code> property.
   * @enum {String}
   * @readonly
   */
  exports.UpgradeEnum = {
    /**
     * value: "NextPeriod"
     * @const
     */
    "NextPeriod": "NextPeriod",
    /**
     * value: "Immediately"
     * @const
     */
    "Immediately": "Immediately",
    /**
     * value: "UserCant"
     * @const
     */
    "UserCant": "UserCant"  };

  /**
   * Allowed values for the <code>downgrade</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DowngradeEnum = {
    /**
     * value: "NextPeriod"
     * @const
     */
    "NextPeriod": "NextPeriod",
    /**
     * value: "Immediately"
     * @const
     */
    "Immediately": "Immediately",
    /**
     * value: "UserCant"
     * @const
     */
    "UserCant": "UserCant"  };


  return exports;
}));


