/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Pack', 'model/Resource'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Pack'), require('./Resource'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.ProductConf = factory(root.S4sFull.ApiClient, root.S4sFull.Pack, root.S4sFull.Resource);
  }
}(this, function(ApiClient, Pack, Resource) {
  'use strict';




  /**
   * The ProductConf model module.
   * @module model/ProductConf
   * @version stable
   */

  /**
   * Constructs a new <code>ProductConf</code>.
   * Model description
   * @alias module:model/ProductConf
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ProductConf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductConf} obj Optional instance to populate.
   * @return {module:model/ProductConf} The populated <code>ProductConf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('resources')) {
        obj['resources'] = ApiClient.convertToType(data['resources'], {'String': Resource});
      }
      if (data.hasOwnProperty('packs')) {
        obj['packs'] = ApiClient.convertToType(data['packs'], {'String': Pack});
      }
    }
    return obj;
  }

  /**
   * @member {Object.<String, module:model/Resource>} resources
   */
  exports.prototype['resources'] = undefined;
  /**
   * @member {Object.<String, module:model/Pack>} packs
   */
  exports.prototype['packs'] = undefined;



  return exports;
}));


