/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.StripeCustomer = factory(root.S4sFull.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StripeCustomer model module.
   * @module model/StripeCustomer
   * @version stable
   */

  /**
   * Constructs a new <code>StripeCustomer</code>.
   * Model description
   * @alias module:model/StripeCustomer
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>StripeCustomer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StripeCustomer} obj Optional instance to populate.
   * @return {module:model/StripeCustomer} The populated <code>StripeCustomer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('creditToken')) {
        obj['creditToken'] = ApiClient.convertToType(data['creditToken'], 'String');
      }
      if (data.hasOwnProperty('client_id')) {
        obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
      }
      if (data.hasOwnProperty('defaultCardLast4')) {
        obj['defaultCardLast4'] = ApiClient.convertToType(data['defaultCardLast4'], 'String');
      }
      if (data.hasOwnProperty('defaultExpMonth')) {
        obj['defaultExpMonth'] = ApiClient.convertToType(data['defaultExpMonth'], 'Integer');
      }
      if (data.hasOwnProperty('defaultExpYear')) {
        obj['defaultExpYear'] = ApiClient.convertToType(data['defaultExpYear'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {String} creditToken
   */
  exports.prototype['creditToken'] = undefined;
  /**
   * @member {String} client_id
   */
  exports.prototype['client_id'] = undefined;
  /**
   * @member {String} defaultCardLast4
   */
  exports.prototype['defaultCardLast4'] = undefined;
  /**
   * @member {Integer} defaultExpMonth
   */
  exports.prototype['defaultExpMonth'] = undefined;
  /**
   * @member {Integer} defaultExpYear
   */
  exports.prototype['defaultExpYear'] = undefined;



  return exports;
}));


