/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GoogleAuth', 'model/UserContact'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./GoogleAuth'), require('./UserContact'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.User = factory(root.S4sFull.ApiClient, root.S4sFull.GoogleAuth, root.S4sFull.UserContact);
  }
}(this, function(ApiClient, GoogleAuth, UserContact) {
  'use strict';




  /**
   * The User model module.
   * @module model/User
   * @version stable
   */

  /**
   * Constructs a new <code>User</code>.
   * Model description
   * @alias module:model/User
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('privateData')) {
        obj['privateData'] = ApiClient.convertToType(data['privateData'], {'String': 'String'});
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], {'String': 'String'});
      }
      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
      }
      if (data.hasOwnProperty('contacts')) {
        obj['contacts'] = UserContact.constructFromObject(data['contacts']);
      }
      if (data.hasOwnProperty('pwd')) {
        obj['pwd'] = ApiClient.convertToType(data['pwd'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('apiTkn')) {
        obj['apiTkn'] = ApiClient.convertToType(data['apiTkn'], 'String');
      }
      if (data.hasOwnProperty('googleAuth')) {
        obj['googleAuth'] = GoogleAuth.constructFromObject(data['googleAuth']);
      }
      if (data.hasOwnProperty('typ')) {
        obj['typ'] = ApiClient.convertToType(data['typ'], 'String');
      }
      if (data.hasOwnProperty('usr')) {
        obj['usr'] = ApiClient.convertToType(data['usr'], 'String');
      }
      if (data.hasOwnProperty('tenantId')) {
        obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Object.<String, String>} privateData
   */
  exports.prototype['privateData'] = undefined;
  /**
   * @member {Object.<String, String>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {String} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * @member {module:model/UserContact} contacts
   */
  exports.prototype['contacts'] = undefined;
  /**
   * @member {String} pwd
   */
  exports.prototype['pwd'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} apiTkn
   */
  exports.prototype['apiTkn'] = undefined;
  /**
   * @member {module:model/GoogleAuth} googleAuth
   */
  exports.prototype['googleAuth'] = undefined;
  /**
   * @member {String} typ
   */
  exports.prototype['typ'] = undefined;
  /**
   * @member {String} usr
   */
  exports.prototype['usr'] = undefined;
  /**
   * @member {String} tenantId
   */
  exports.prototype['tenantId'] = undefined;



  return exports;
}));


