/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.UserEntity = factory(root.S4sFull.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserEntity model module.
   * @module model/UserEntity
   * @version stable
   */

  /**
   * Constructs a new <code>UserEntity</code>.
   * Model description
   * @alias module:model/UserEntity
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>UserEntity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserEntity} obj Optional instance to populate.
   * @return {module:model/UserEntity} The populated <code>UserEntity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('accountId')) {
        obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
      }
      if (data.hasOwnProperty('_typ')) {
        obj['_typ'] = ApiClient.convertToType(data['_typ'], 'String');
      }
      if (data.hasOwnProperty('usr')) {
        obj['usr'] = ApiClient.convertToType(data['usr'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} accountId
   */
  exports.prototype['accountId'] = undefined;
  /**
   * @member {module:model/UserEntity.TypEnum} _typ
   */
  exports.prototype['_typ'] = undefined;
  /**
   * @member {String} usr
   */
  exports.prototype['usr'] = undefined;


  /**
   * Allowed values for the <code>_typ</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypEnum = {
    /**
     * value: "UserApi"
     * @const
     */
    "UserApi": "UserApi",
    /**
     * value: "User"
     * @const
     */
    "User": "User"  };


  return exports;
}));


