/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.S4sFull) {
      root.S4sFull = {};
    }
    root.S4sFull.UserUiConf = factory(root.S4sFull.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserUiConf model module.
   * @module model/UserUiConf
   * @version stable
   */

  /**
   * Constructs a new <code>UserUiConf</code>.
   * Model description
   * @alias module:model/UserUiConf
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>UserUiConf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserUiConf} obj Optional instance to populate.
   * @return {module:model/UserUiConf} The populated <code>UserUiConf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('googleClientId')) {
        obj['googleClientId'] = ApiClient.convertToType(data['googleClientId'], 'String');
      }
      if (data.hasOwnProperty('googleClientKey')) {
        obj['googleClientKey'] = ApiClient.convertToType(data['googleClientKey'], 'String');
      }
      if (data.hasOwnProperty('loginUrl')) {
        obj['loginUrl'] = ApiClient.convertToType(data['loginUrl'], 'String');
      }
      if (data.hasOwnProperty('basePath')) {
        obj['basePath'] = ApiClient.convertToType(data['basePath'], 'String');
      }
      if (data.hasOwnProperty('changePasswordUrl')) {
        obj['changePasswordUrl'] = ApiClient.convertToType(data['changePasswordUrl'], 'String');
      }
      if (data.hasOwnProperty('registerUrl')) {
        obj['registerUrl'] = ApiClient.convertToType(data['registerUrl'], 'String');
      }
      if (data.hasOwnProperty('recoverPasswordUrl')) {
        obj['recoverPasswordUrl'] = ApiClient.convertToType(data['recoverPasswordUrl'], 'String');
      }
      if (data.hasOwnProperty('loginHandler')) {
        obj['loginHandler'] = ApiClient.convertToType(data['loginHandler'], 'String');
      }
      if (data.hasOwnProperty('subscribeUrl')) {
        obj['subscribeUrl'] = ApiClient.convertToType(data['subscribeUrl'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} googleClientId
   */
  exports.prototype['googleClientId'] = undefined;
  /**
   * @member {String} googleClientKey
   */
  exports.prototype['googleClientKey'] = undefined;
  /**
   * @member {String} loginUrl
   */
  exports.prototype['loginUrl'] = undefined;
  /**
   * @member {String} basePath
   */
  exports.prototype['basePath'] = undefined;
  /**
   * @member {String} changePasswordUrl
   */
  exports.prototype['changePasswordUrl'] = undefined;
  /**
   * @member {String} registerUrl
   */
  exports.prototype['registerUrl'] = undefined;
  /**
   * @member {String} recoverPasswordUrl
   */
  exports.prototype['recoverPasswordUrl'] = undefined;
  /**
   * @member {String} loginHandler
   */
  exports.prototype['loginHandler'] = undefined;
  /**
   * @member {String} subscribeUrl
   */
  exports.prototype['subscribeUrl'] = undefined;



  return exports;
}));


