/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S4sFull);
  }
}(this, function(expect, S4sFull) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new S4sFull.CustomerPack();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomerPack', function() {
    it('should create an instance of CustomerPack', function() {
      // uncomment below and update the code to test CustomerPack
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be.a(S4sFull.CustomerPack);
    });

    it('should have the property closedTime (base name: "closedTime")', function() {
      // uncomment below and update the code to test the property closedTime
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property resourceStatuList (base name: "resourceStatuList")', function() {
      // uncomment below and update the code to test the property resourceStatuList
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionId (base name: "subscriptionId")', function() {
      // uncomment below and update the code to test the property subscriptionId
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property expirationTimeSpan (base name: "expirationTimeSpan")', function() {
      // uncomment below and update the code to test the property expirationTimeSpan
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customerId")', function() {
      // uncomment below and update the code to test the property customerId
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property exactConfId (base name: "exactConfId")', function() {
      // uncomment below and update the code to test the property exactConfId
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property packId (base name: "packId")', function() {
      // uncomment below and update the code to test the property packId
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property spent (base name: "spent")', function() {
      // uncomment below and update the code to test the property spent
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

    it('should have the property creationTime (base name: "creationTime")', function() {
      // uncomment below and update the code to test the property creationTime
      //var instane = new S4sFull.CustomerPack();
      //expect(instance).to.be();
    });

  });

}));
