/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S4sFull);
  }
}(this, function(expect, S4sFull) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new S4sFull.PaymentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentRequest', function() {
    it('should create an instance of PaymentRequest', function() {
      // uncomment below and update the code to test PaymentRequest
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be.a(S4sFull.PaymentRequest);
    });

    it('should have the property creationTimespan (base name: "creationTimespan")', function() {
      // uncomment below and update the code to test the property creationTimespan
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property paidTimespan (base name: "paidTimespan")', function() {
      // uncomment below and update the code to test the property paidTimespan
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property whatPays (base name: "whatPays")', function() {
      // uncomment below and update the code to test the property whatPays
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property billId (base name: "billId")', function() {
      // uncomment below and update the code to test the property billId
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customerId")', function() {
      // uncomment below and update the code to test the property customerId
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property stripeChargeId (base name: "stripeChargeId")', function() {
      // uncomment below and update the code to test the property stripeChargeId
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instane = new S4sFull.PaymentRequest();
      //expect(instance).to.be();
    });

  });

}));
