/**
 * s4s-full
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.S4sFull);
  }
}(this, function(expect, S4sFull) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new S4sFull.SsPaymentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SsPaymentApi', function() {
    describe('conf', function() {
      it('should call conf successfully', function(done) {
        //uncomment below and update the code to test conf
        //instance.conf(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerInfoCurrency', function() {
      it('should call customerInfoCurrency successfully', function(done) {
        //uncomment below and update the code to test customerInfoCurrency
        //instance.customerInfoCurrency(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerInfoGet', function() {
      it('should call customerInfoGet successfully', function(done) {
        //uncomment below and update the code to test customerInfoGet
        //instance.customerInfoGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerInfoHasPaymentInfo', function() {
      it('should call customerInfoHasPaymentInfo successfully', function(done) {
        //uncomment below and update the code to test customerInfoHasPaymentInfo
        //instance.customerInfoHasPaymentInfo(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerInfoStripeCustomer', function() {
      it('should call customerInfoStripeCustomer successfully', function(done) {
        //uncomment below and update the code to test customerInfoStripeCustomer
        //instance.customerInfoStripeCustomer(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerPaymentAdd', function() {
      it('should call customerPaymentAdd successfully', function(done) {
        //uncomment below and update the code to test customerPaymentAdd
        //instance.customerPaymentAdd(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerPaymentCancelPatch', function() {
      it('should call customerPaymentCancelPatch successfully', function(done) {
        //uncomment below and update the code to test customerPaymentCancelPatch
        //instance.customerPaymentCancelPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerPaymentGet', function() {
      it('should call customerPaymentGet successfully', function(done) {
        //uncomment below and update the code to test customerPaymentGet
        //instance.customerPaymentGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerPaymentPayPatch', function() {
      it('should call customerPaymentPayPatch successfully', function(done) {
        //uncomment below and update the code to test customerPaymentPayPatch
        //instance.customerPaymentPayPatch(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('customerPaymentValues', function() {
      it('should call customerPaymentValues successfully', function(done) {
        //uncomment below and update the code to test customerPaymentValues
        //instance.customerPaymentValues(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentConfigGet', function() {
      it('should call paymentConfigGet successfully', function(done) {
        //uncomment below and update the code to test paymentConfigGet
        //instance.paymentConfigGet(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentConfigPut', function() {
      it('should call paymentConfigPut successfully', function(done) {
        //uncomment below and update the code to test paymentConfigPut
        //instance.paymentConfigPut(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paymentGetAll', function() {
      it('should call paymentGetAll successfully', function(done) {
        //uncomment below and update the code to test paymentGetAll
        //instance.paymentGetAll(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
